### ISSUE TITLE
Adding sliver sample widgets

### ISSUE THREAD

**Issue by mcz9mm** [mafreud/proximity#1]
# Motivation
I would like to implement a basic sample page for Sliver.

## Widgets
- [x] SliverAppBar
- [x] SliverGrid
- [x] SliverToBoxAdapter
- [x] SliverList

## GIf 🎥
![sliver](https://user-images.githubusercontent.com/11751495/116700492-cb740680-aa01-11eb-89f1-e6f5a067fbc5.gif)

## Ref
https://flutter.dev/docs/development/ui/advanced/slivers

**Comment by mafreud** [comment]
Thank you for your contribution. I will review your pr asap 😄
